FROM centos:centos7.9.2009
RUN yum -y install java
RUN mkdir /opt/tomcat
WORKDIR /opt/tomcat
RUN yum install wget -y
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.84/bin/apache-tomcat-8.5.84.tar.gz .
RUN tar -xvzf apache-tomcat-8.5.84.tar.gz
RUN mv apache-tomcat-8.5.84/* /opt/tomcat
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
